# ENGINE CONFIG
#
SATENOBJ = src/saturn_engine/core/_engine.c
SATENOBJ += src/saturn_engine/core/audio.c
SATENOBJ += src/saturn_engine/core/controller.c
SATENOBJ += src/saturn_engine/core/darray.c
SATENOBJ += src/saturn_engine/core/draw.c
SATENOBJ += src/saturn_engine/core/error.c
SATENOBJ += src/saturn_engine/core/flag.c
SATENOBJ += src/saturn_engine/core/framerate.c
SATENOBJ += src/saturn_engine/core/haptic.c
SATENOBJ += src/saturn_engine/core/input.c
SATENOBJ += src/saturn_engine/core/keyboard.c
SATENOBJ += src/saturn_engine/core/layer.c
SATENOBJ += src/saturn_engine/core/list.c
SATENOBJ += src/saturn_engine/core/mruby.c
SATENOBJ += src/saturn_engine/core/pixel.c
SATENOBJ += src/saturn_engine/core/sprite.c
SATENOBJ += src/saturn_engine/core/surface.c
SATENOBJ += src/saturn_engine/core/text.c
SATENOBJ += src/saturn_engine/core/util.c
SATENOBJ += src/saturn_engine/core/mfield.c
SATENOBJ += src/saturn_engine/core/crypt.c
SATENOBJ += src/saturn_engine/core/window.c
SATENOBJ += src/saturn_engine/core/texture.c
SATENOBJ += src/saturn_engine/core/renderer.c
SATENOBJ += src/saturn_engine/core/music.c
SATENOBJ += src/saturn_engine/core/sound.c


SATENOBJ += src/saturn_engine/_engine.c
SATENOBJ += src/saturn_engine/mruby.c
SATENOBJ += src/saturn_engine/load.c
SATENOBJ += src/saturn_engine/resource.c
SATENOBJ += src/saturn_engine/scene.c
SATENOBJ += src/saturn_engine/sfx.c
SATENOBJ += src/saturn_engine/data.c
SATENOBJ += src/saturn_engine/video.c
SATENOBJ += src/saturn_engine/player.c
SATENOBJ += src/saturn_engine/plane.c
SATENOBJ += src/saturn_engine/bgm.c
SATENOBJ += src/saturn_engine/menu.c
