#ifndef SATURN_ENGINE_CORE_CONFIG
#define SATURN_ENGINE_CORE_CONFIG

#define SATEN_CORE_TEXT_WSPACE_WIDTH_DEFAULT 8
#define SATEN_CORE_TEXT_XPAD_DEFAULT 2
#define SATEN_CORE_TEXT_YPAD_DEFAULT 2

#endif /* SATURN_ENGINE_CORE_CONFIG */
