#ifndef SATURN_ENGINE_CONFIG_MENU
#define SATURN_ENGINE_CONFIG_MENU

#define SATEN_CONF_MENU_ROWLEN_DEFAULT 4
#define SATEN_CONF_MENU_COLLEN_DEFAULT 1
#define SATEN_CONF_MENU_HPADDING_DEFAULT 16
#define SATEN_CONF_MENU_VPADDING_DEFAULT 16


#endif /* SATURN_ENGINE_CONFIG_MENU */
